[tool.uv.workspace]
members = [
    "libraries/ban_carbon_common",
    "projects/*"
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "ruff",
    "mkdocs",
]

[tool.ruff]
line-length = 99
src = ["libraries/*/src", "projects/*/src"]
include = ["pyproject.toml", "libraries/**/*.py", "projects/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["ban_carbon_common"]
force-sort-within-sections = true
